/**
 * Dart code tab content keyed by [slug] from `showcase-manifest.json`.
 * Keep in sync with `example/lib/showcase/config/*_public_config.dart` and `doc-code-snippets/*.ts`.
 */
import {
  accordionCustomIndicatorCode,
  accordionCustomIndicatorVariantsCode,
  accordionCustomRenderCode,
  accordionCustomStylesCode,
  accordionDisabledItemsCode,
  accordionDisabledRootCode,
  accordionFaqCode,
  accordionFaqLayoutCode,
  accordionMultipleCode,
  accordionSurfaceCode,
  accordionWithoutSeparatorCode,
} from "./doc-code-snippets/accordion";
import {
  alertAccentCode,
  alertCustomIndicatorCode,
  alertDangerCode,
  alertSuccessCode,
  alertUsageCode,
  alertWarningCode,
  alertWithoutCloseCode,
  alertWithoutDescriptionCode,
  alertWithActionsCode,
} from "./doc-code-snippets/alert";
import {
  avatarColorsCode,
  avatarCustomStylesCode,
  avatarFallbackCode,
  avatarGroupCode,
  avatarSizesCode,
  avatarUsageCode,
  avatarVariantsCode,
  avatarWithDelayCode,
} from "./doc-code-snippets/avatar";
import {
  buttonCompoundLabelCode,
  buttonDisabledCode,
  buttonFullWidthCode,
  buttonIconOnlyCode,
  buttonLoadingCode,
  buttonLoadingStateCode,
  buttonSizesCode,
  buttonSocialButtonsCode,
  buttonUsageCode,
  buttonVariantsCode,
  buttonWithIconsCode,
} from "./doc-code-snippets/button";
import {
  closeButtonInteractiveCode,
  closeButtonUsageCode,
  closeButtonWithCustomIconCode,
} from "./doc-code-snippets/close-button";
import {
  chipSizesCode,
  chipStatusesCode,
  chipUsageCode,
  chipVariantsCode,
  chipWithIconsCode,
} from "./doc-code-snippets/chip";
import {
  cardHorizontalCode,
  cardUsageCode,
  cardVariantsCode,
  cardWithAvatarCode,
  cardWithFormCode,
  cardWithImagesCode,
} from "./doc-code-snippets/card";
import {
  tagGroupControlledCode,
  tagGroupDisabledCode,
  tagGroupSelectionModesCode,
  tagGroupSizesCode,
  tagGroupUsageCode,
  tagGroupVariantsCode,
  tagGroupWithErrorCode,
  tagGroupWithIconsCode,
  tagGroupWithListDataCode,
  tagGroupWithRemoveCode,
} from "./doc-code-snippets/tag-group";
import {
  sliderCustomFormatCode,
  sliderDisabledCode,
  sliderRangeCode,
  sliderUsageCode,
  sliderVerticalCode,
} from "./doc-code-snippets/slider";
import {
  skeletonAnimationTypesCode,
  skeletonGridCode,
  skeletonListItemsCode,
  skeletonSynchronizedShimmerCode,
  skeletonTextContentCode,
  skeletonUsageCode,
  skeletonUserProfileCode,
} from "./doc-code-snippets/skeleton";
import {
  spinnerColorsCode,
  spinnerLoadingFlagCode,
  spinnerSizesCode,
  spinnerUsageCode,
} from "./doc-code-snippets/spinner";
import { surfaceUsageCode, surfaceWithFormCode } from "./doc-code-snippets/surface";
import {
  switchControlledCode,
  switchDisabledCode,
  switchGroupCode,
  switchGroupHorizontalCode,
  switchLabelPositionCode,
  switchRenderPropsCode,
  switchSizesCode,
  switchUsageCode,
  switchWithoutLabelCode,
  switchWithCustomStylesCode,
  switchWithDescriptionCode,
  switchWithIconsCode,
} from "./doc-code-snippets/switch";
import {
  tabsCustomStylesCode,
  tabsDisabledCode,
  tabsScrollableCode,
  tabsSecondaryCode,
  tabsSecondaryVerticalCode,
  tabsUsageCode,
  tabsVerticalCode,
} from "./doc-code-snippets/tabs";
import {
  toastHeroStoriesCode,
  toastLoadingCode,
  toastPlacementsCode,
} from "./doc-code-snippets/toast";
import {
  checkboxControlledCode,
  checkboxCustomIndicatorCode,
  checkboxDisabledCode,
  checkboxFeaturesCode,
  checkboxIndeterminateCode,
  checkboxInvalidCode,
  checkboxRenderPropsCode,
  checkboxSizesCode,
  checkboxUsageCode,
  checkboxVariantsCode,
  checkboxWithDescriptionCode,
} from "./doc-code-snippets/checkbox";
import {
  descriptionLongWrapCode,
  descriptionUsageCode,
  descriptionWithFormFieldCode,
  descriptionWithTextFieldCode,
} from "./doc-code-snippets/description";
import {
  fieldErrorBasicValidationCode,
  fieldErrorDynamicMessageCode,
  fieldErrorMultipleMessagesCode,
  fieldErrorUsageCode,
  fieldErrorVisibilityCode,
} from "./doc-code-snippets/field-error";
import {
  labelControlFieldCode,
  labelCustomIndicatorCode,
  labelDisabledCode,
  labelInvalidCode,
  labelRequiredCode,
  labelRequiredInvalidCode,
  labelUsageCode,
  labelWithDescriptionCode,
  labelWithInputCode,
} from "./doc-code-snippets/label";
import {
  popoverCardHelpCode,
  popoverCustomTriggerCode,
  popoverInteractiveContentCode,
  popoverPlacementCode,
  popoverUsageCode,
  popoverWithArrowCode,
} from "./doc-code-snippets/popover";
import {
  radioControlledCode,
  radioDisabledCode,
  radioHorizontalCode,
  radioInvalidCode,
  radioOnSurfaceCode,
  radioUncontrolledCode,
  radioUsageCode,
  radioValidationCode,
  radioVariantsCode,
} from "./doc-code-snippets/radio";
import {
  searchFieldControlledCode,
  searchFieldDisabledCode,
  searchFieldFullWidthCode,
  searchFieldRequiredCode,
  searchFieldUsageCode,
  searchFieldValidationCode,
  searchFieldVariantsCode,
  searchFieldWithDescriptionCode,
} from "./doc-code-snippets/search-field";
import {
  selectDisabledCode,
  selectFullWidthCode,
  selectRequiredCode,
  selectUsageCode,
  selectVariantsCode,
  selectWithDescriptionCode,
  selectWithDisabledOptionsCode,
} from "./doc-code-snippets/select";
import {
  scrollShadowCustomSizeCode,
  scrollShadowHideScrollbarCode,
  scrollShadowOrientationCode,
  scrollShadowUsageCode,
  scrollShadowVariantsCode,
  scrollShadowVisibilityStateCode,
  scrollShadowWithCardCode,
} from "./doc-code-snippets/scroll-shadow";
import {
  separatorUsageCode,
  separatorVariantsCode,
  separatorVerticalCode,
  separatorWithContentCode,
  separatorWithSurfaceCode,
} from "./doc-code-snippets/separator";
import {
  inputControlledCode,
  inputDisabledCode,
  inputFullWidthCode,
  inputInvalidCode,
  inputOnSurfacesCode,
  inputTypesCode,
  inputUsageCode,
  inputVariantsCode,
} from "./doc-code-snippets/input";
import {
  inputGroupBadgeSuffixCode,
  inputGroupCopySuffixCode,
  inputGroupDisabledCode,
  inputGroupFullWidthCode,
  inputGroupIconPrefixCopySuffixCode,
  inputGroupIconPrefixTextSuffixCode,
  inputGroupInvalidCode,
  inputGroupKeyboardShortcutCode,
  inputGroupLoadingCode,
  inputGroupPasswordToggleCode,
  inputGroupPrefixAndSuffixCode,
  inputGroupRequiredFieldCode,
  inputGroupTextPrefixCode,
  inputGroupTextSuffixCode,
  inputGroupUsageCode,
  inputGroupValidationCode,
  inputGroupVariantsCode,
  inputGroupWithSuffixCode,
} from "./doc-code-snippets/input-group";
import {
  inputOtpControlledCode,
  inputOtpDisabledCode,
  inputOtpFormExampleCode,
  inputOtpFourDigitsCode,
  inputOtpOnCompleteCode,
  inputOtpUsageCode,
  inputOtpVariantsCode,
  inputOtpWithPatternCode,
  inputOtpWithValidationCode,
} from "./doc-code-snippets/input-otp";
import {
  textAreaControlledCode,
  textAreaFullWidthCode,
  textAreaRowsCode,
  textAreaUsageCode,
  textAreaVariantsCode,
} from "./doc-code-snippets/text-area";
import {
  textFieldControlledCode,
  textFieldDisabledCode,
  textFieldErrorMessageCode,
  textFieldFullWidthCode,
  textFieldInSurfaceCode,
  textFieldInputTypesCode,
  textFieldMultilineCode,
  textFieldRequiredCode,
  textFieldUsageCode,
  textFieldValidationCode,
  textFieldVariantsCode,
  textFieldWithDescriptionCode,
} from "./doc-code-snippets/text-field";

export const showcaseCodeByComponent: Record<string, Record<string, string>> = {
  accordion: {
    faq: accordionFaqCode,
    surface: accordionSurfaceCode,
    multiple: accordionMultipleCode,
    "custom-indicator": accordionCustomIndicatorCode,
    "custom-indicator-variants": accordionCustomIndicatorVariantsCode,
    "disabled-root": accordionDisabledRootCode,
    "disabled-items": accordionDisabledItemsCode,
    "without-separator": accordionWithoutSeparatorCode,
    "custom-render": accordionCustomRenderCode,
    "faq-layout": accordionFaqLayoutCode,
    "custom-styles": accordionCustomStylesCode,
  },
  alert: {
    usage: alertUsageCode,
    accent: alertAccentCode,
    success: alertSuccessCode,
    warning: alertWarningCode,
    danger: alertDangerCode,
    "without-description": alertWithoutDescriptionCode,
    "custom-indicator": alertCustomIndicatorCode,
    "without-close": alertWithoutCloseCode,
    "with-actions": alertWithActionsCode,
  },
  avatar: {
    usage: avatarUsageCode,
    "with-delay": avatarWithDelayCode,
    sizes: avatarSizesCode,
    colors: avatarColorsCode,
    variants: avatarVariantsCode,
    fallback: avatarFallbackCode,
    group: avatarGroupCode,
    "custom-styles": avatarCustomStylesCode,
  },
  button: {
    usage: buttonUsageCode,
    variants: buttonVariantsCode,
    "with-icons": buttonWithIconsCode,
    "icon-only": buttonIconOnlyCode,
    loading: buttonLoadingCode,
    "loading-state": buttonLoadingStateCode,
    sizes: buttonSizesCode,
    "full-width": buttonFullWidthCode,
    disabled: buttonDisabledCode,
    "social-buttons": buttonSocialButtonsCode,
    "compound-label": buttonCompoundLabelCode,
  },
  "close-button": {
    usage: closeButtonUsageCode,
    "with-custom-icon": closeButtonWithCustomIconCode,
    interactive: closeButtonInteractiveCode,
  },
  chip: {
    usage: chipUsageCode,
    sizes: chipSizesCode,
    "with-icons": chipWithIconsCode,
    statuses: chipStatusesCode,
    variants: chipVariantsCode,
  },
  card: {
    usage: cardUsageCode,
    variants: cardVariantsCode,
    horizontal: cardHorizontalCode,
    "with-avatar": cardWithAvatarCode,
    "with-images": cardWithImagesCode,
    "with-form": cardWithFormCode,
  },
  "tag-group": {
    usage: tagGroupUsageCode,
    sizes: tagGroupSizesCode,
    variants: tagGroupVariantsCode,
    disabled: tagGroupDisabledCode,
    "selection-modes": tagGroupSelectionModesCode,
    controlled: tagGroupControlledCode,
    "with-icons": tagGroupWithIconsCode,
    "with-remove": tagGroupWithRemoveCode,
    "with-error": tagGroupWithErrorCode,
    "with-list-data": tagGroupWithListDataCode,
  },
  slider: {
    usage: sliderUsageCode,
    vertical: sliderVerticalCode,
    range: sliderRangeCode,
    disabled: sliderDisabledCode,
    "custom-format": sliderCustomFormatCode,
  },
  skeleton: {
    usage: skeletonUsageCode,
    "text-content": skeletonTextContentCode,
    "user-profile": skeletonUserProfileCode,
    "list-items": skeletonListItemsCode,
    "animation-types": skeletonAnimationTypesCode,
    grid: skeletonGridCode,
    "synchronized-shimmer": skeletonSynchronizedShimmerCode,
  },
  spinner: {
    usage: spinnerUsageCode,
    colors: spinnerColorsCode,
    sizes: spinnerSizesCode,
    "loading-flag": spinnerLoadingFlagCode,
  },
  surface: {
    usage: surfaceUsageCode,
    "with-form": surfaceWithFormCode,
  },
  switch: {
    usage: switchUsageCode,
    disabled: switchDisabledCode,
    controlled: switchControlledCode,
    "without-label": switchWithoutLabelCode,
    sizes: switchSizesCode,
    "label-position": switchLabelPositionCode,
    "with-description": switchWithDescriptionCode,
    "with-custom-styles": switchWithCustomStylesCode,
    "with-icons": switchWithIconsCode,
    "render-props": switchRenderPropsCode,
    group: switchGroupCode,
    "group-horizontal": switchGroupHorizontalCode,
  },
  tabs: {
    usage: tabsUsageCode,
    vertical: tabsVerticalCode,
    disabled: tabsDisabledCode,
    "custom-styles": tabsCustomStylesCode,
    secondary: tabsSecondaryCode,
    "secondary-vertical": tabsSecondaryVerticalCode,
    scrollable: tabsScrollableCode,
  },
  toast: {
    "hero-stories": toastHeroStoriesCode,
    placements: toastPlacementsCode,
    loading: toastLoadingCode,
  },
  checkbox: {
    usage: checkboxUsageCode,
    controlled: checkboxControlledCode,
    indeterminate: checkboxIndeterminateCode,
    "with-description": checkboxWithDescriptionCode,
    invalid: checkboxInvalidCode,
    variants: checkboxVariantsCode,
    disabled: checkboxDisabledCode,
    "custom-indicator": checkboxCustomIndicatorCode,
    "render-props": checkboxRenderPropsCode,
    sizes: checkboxSizesCode,
    features: checkboxFeaturesCode,
  },
  description: {
    usage: descriptionUsageCode,
    "with-form-field": descriptionWithFormFieldCode,
    "with-text-field": descriptionWithTextFieldCode,
    "long-wrap": descriptionLongWrapCode,
  },
  "field-error": {
    usage: fieldErrorUsageCode,
    visibility: fieldErrorVisibilityCode,
    "basic-validation": fieldErrorBasicValidationCode,
    "dynamic-message": fieldErrorDynamicMessageCode,
    "multiple-messages": fieldErrorMultipleMessagesCode,
  },
  label: {
    usage: labelUsageCode,
    required: labelRequiredCode,
    disabled: labelDisabledCode,
    invalid: labelInvalidCode,
    "with-input": labelWithInputCode,
    "with-description": labelWithDescriptionCode,
    "required-invalid": labelRequiredInvalidCode,
    "custom-indicator": labelCustomIndicatorCode,
    "control-field": labelControlFieldCode,
  },
  popover: {
    usage: popoverUsageCode,
    "with-arrow": popoverWithArrowCode,
    placement: popoverPlacementCode,
    "interactive-content": popoverInteractiveContentCode,
    "custom-trigger": popoverCustomTriggerCode,
    "card-help": popoverCardHelpCode,
  },
  radio: {
    usage: radioUsageCode,
    horizontal: radioHorizontalCode,
    controlled: radioControlledCode,
    uncontrolled: radioUncontrolledCode,
    validation: radioValidationCode,
    disabled: radioDisabledCode,
    variants: radioVariantsCode,
    invalid: radioInvalidCode,
    "on-surface": radioOnSurfaceCode,
  },
  "search-field": {
    usage: searchFieldUsageCode,
    "with-description": searchFieldWithDescriptionCode,
    required: searchFieldRequiredCode,
    validation: searchFieldValidationCode,
    disabled: searchFieldDisabledCode,
    controlled: searchFieldControlledCode,
    "full-width": searchFieldFullWidthCode,
    variants: searchFieldVariantsCode,
  },
  select: {
    usage: selectUsageCode,
    "with-description": selectWithDescriptionCode,
    "with-disabled-options": selectWithDisabledOptionsCode,
    required: selectRequiredCode,
    "full-width": selectFullWidthCode,
    variants: selectVariantsCode,
    disabled: selectDisabledCode,
  },
  "scroll-shadow": {
    usage: scrollShadowUsageCode,
    variants: scrollShadowVariantsCode,
    orientation: scrollShadowOrientationCode,
    "hide-scrollbar": scrollShadowHideScrollbarCode,
    "custom-size": scrollShadowCustomSizeCode,
    "visibility-state": scrollShadowVisibilityStateCode,
    "with-card": scrollShadowWithCardCode,
  },
  separator: {
    usage: separatorUsageCode,
    vertical: separatorVerticalCode,
    "with-content": separatorWithContentCode,
    variants: separatorVariantsCode,
    "with-surface": separatorWithSurfaceCode,
  },
  input: {
    usage: inputUsageCode,
    variants: inputVariantsCode,
    "input-types": inputTypesCode,
    controlled: inputControlledCode,
    "full-width": inputFullWidthCode,
    "on-surfaces": inputOnSurfacesCode,
    invalid: inputInvalidCode,
    disabled: inputDisabledCode,
  },
  "input-group": {
    usage: inputGroupUsageCode,
    "text-prefix": inputGroupTextPrefixCode,
    "text-suffix": inputGroupTextSuffixCode,
    "icon-prefix-text-suffix": inputGroupIconPrefixTextSuffixCode,
    "copy-suffix": inputGroupCopySuffixCode,
    "icon-prefix-copy-suffix": inputGroupIconPrefixCopySuffixCode,
    loading: inputGroupLoadingCode,
    "keyboard-shortcut": inputGroupKeyboardShortcutCode,
    "badge-suffix": inputGroupBadgeSuffixCode,
    "required-field": inputGroupRequiredFieldCode,
    validation: inputGroupValidationCode,
    disabled: inputGroupDisabledCode,
    "with-suffix": inputGroupWithSuffixCode,
    "prefix-and-suffix": inputGroupPrefixAndSuffixCode,
    "password-toggle": inputGroupPasswordToggleCode,
    variants: inputGroupVariantsCode,
    "full-width": inputGroupFullWidthCode,
    invalid: inputGroupInvalidCode,
  },
  "input-otp": {
    usage: inputOtpUsageCode,
    "four-digits": inputOtpFourDigitsCode,
    disabled: inputOtpDisabledCode,
    "with-pattern": inputOtpWithPatternCode,
    controlled: inputOtpControlledCode,
    variants: inputOtpVariantsCode,
    "with-validation": inputOtpWithValidationCode,
    "on-complete": inputOtpOnCompleteCode,
    "form-example": inputOtpFormExampleCode,
  },
  "text-area": {
    usage: textAreaUsageCode,
    controlled: textAreaControlledCode,
    rows: textAreaRowsCode,
    "full-width": textAreaFullWidthCode,
    variants: textAreaVariantsCode,
  },
  "text-field": {
    usage: textFieldUsageCode,
    "with-description": textFieldWithDescriptionCode,
    required: textFieldRequiredCode,
    validation: textFieldValidationCode,
    controlled: textFieldControlledCode,
    "error-message": textFieldErrorMessageCode,
    disabled: textFieldDisabledCode,
    multiline: textFieldMultilineCode,
    "input-types": textFieldInputTypesCode,
    "full-width": textFieldFullWidthCode,
    "in-surface": textFieldInSurfaceCode,
    variants: textFieldVariantsCode,
  },
};
