name: rise_ui
description: RiseUI — a minimal, HeroUI-inspired Flutter component library.
version: 0.1.0
homepage:

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_drawing: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
